# Generated by Django 2.2.13 on 2020-08-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortreview', models.CharField(max_length=200)),
                ('stars', models.CharField(max_length=5)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
